# A list of devices you want to take the screenshots from
devices([
  "iPhone 6",
  "iPhone 6 Plus",
  "iPhone 5",
  "iPad Air",
])

languages([
  "en-US",
])

scheme "Anime Detour"

output_directory "./fastlane/screenshots"

clear_previous_screenshots true

workspace "./Anime Detour.xcworkspace"
